defineSourceFiles([
  'src/helpers/assert.js',
  'src/helpers/is.js',
  'src/helpers.js',
  'src/linq.js',
  'src/math.js',
  'src/concatenation.js',
  'src/search.js',
  'src/access.js',
  'src/heap.js',
  'src/order.js',
  'src/transformation.js',
])
